# UCA Mashburn Room 238 Acoustic Analysis

This notebook is to analyze the balloon-pop impulse acoustic data from the UCA Mashburn Hall Room 238.

Date: April 27, 2026

### Initialize the acoustics library 

The library description and information can be found on Github at: https://github.com/python-acoustics/python-acoustics

In [1]:
from acoustics import bands,room

#octave(first octave center frequency,last octave center frequency)

octave_bands = bands.octave(125,4000)
print(octave_bands)

[ 125.  250.  500. 1000. 2000. 4000.]


### Room Response No Treatment

In [2]:
import numpy as np
#t60_impulse(file_name, bands, rt='t30'):  # pylint: disable=too-many-locals
"""
Reverberation time from a WAV impulse response.
:param file_name: name of the WAV file containing the impulse response.
:param bands: Octave or third bands as NumPy array.
:param rt: Reverberation time estimator. It accepts `'t30'`, `'t20'`, `'t10'` and `'edt'`.
:returns: Reverberation time :math:`T_{60}`
"""

t60_bands_run_0_a = room.t60_impulse('Trial-1-No-Treatment.wav',octave_bands,rt='t30')
t60_bands_run_0_b = room.t60_impulse('Trial-2-No-Treatment.wav',octave_bands,rt='t30')
t60_bands_run_0_c = room.t60_impulse('Trial-3-No-Treatment.wav',octave_bands,rt='t30')
print(t60_bands_run_0_a)
print(t60_bands_run_0_b)
print(t60_bands_run_0_c)

t60_bands_run_0_ave = np.zeros(len(octave_bands))
for i in range(len(octave_bands)):
    ave = (t60_bands_run_0_a[i] + t60_bands_run_0_b[i] + t60_bands_run_0_c[i]) / 3
    t60_bands_run_0_ave[i] = round(ave,1)

print('average reverb times =', t60_bands_run_0_ave)

[1.36246852 1.13362525 1.17777834 0.9635626  0.77020801 0.65917797]
[1.06765742 1.16548195 1.08326745 0.94699779 0.76737561 0.62527379]
[1.17889913 1.07966069 1.18043472 0.95273784 0.80311871 0.63344949]
average reverb times = [1.2 1.1 1.1 1.  0.8 0.6]
